Update RSD Home with Video and new styles tweaks
research-software-directory/RSD-as-a-service pull request #1051
Opened 2023-11-14 15:42 UTC by ctwhome

Fixes #1016

Changes proposed in this pull request:

- New video files for the RSD video section 
- Add new styles for specifiv buttons and icons. 
- This pull request includes updates to the RSD Home stats layout to improve responsiveness. 
- It also adds new background size and position utilities to tailwind.config.js. 
- Some code refactoring for improved readability and efficiency. 

PR Checklist:

*   [ ] Increase version numbers in `docker-compose.yml`
*   [x] Link to a GitHub issue
*   [ ] Update documentation
*   [ ] Tests

2023-11-14 16:35 UTC, dmijatovic commented on frontend/tailwind.config.js
> +const defaultSettings = require("./public/data/settings.json");
Can you run this file through the linter? It seem that it uses different formatting, not sure why?

2023-11-14 16:54 UTC, dmijatovic commented on frontend/components/home/rsd/index.tsx
> +      <div className="max-w-screen-xl mx-auto p-5  grid lg:grid-cols-[1fr,1fr] gap-8 md:gap-20 md:my-28">
Maybe add 1/2 grid ratio for large screens `xl:grid-cols-[1fr,2fr]`? I find the vertical margins quite large. Not sure what other think?

2023-11-14 17:11 UTC, dmijatovic commented on frontend/components/home/rsd/index.tsx
> +    </div >
It seems that my VSC formatter does not add the spaces in the html tags and yours does. Not sure why eslint formatting is different. This is not important just an observation.

2023-11-14 17:16 UTC, dmijatovic approved these changes
Nice work!
I posted few minor remarks but nothing critical. 
It would be also nice if you could squash it into one commit. 
I think you can also squash it into one commit during the merge?

2023-11-14 17:47 UTC, jmaassen requested changes
Looks great. Two comments though:

- at the moment, the video only shows the NLESC logo for "developed by". It would be nice to also include Helmholtz there? We should ask Christian if he also feels this is a good idea, and which logo we should use (the HIFIS one for example)
- I'm not sure about the new buttons for demo, docs, etc. They're not "button enough" for me. 

![Screenshot 2023-11-14 at 18-44-08 Home Research Software Directory](https://github.com/research-software-directory/RSD-as-a-service/assets/1705533/857b428f-5781-40f3-b282-d16b3d8c38ef)

2023-11-14 19:34 UTC, ctwhome commented on frontend/components/home/rsd/index.tsx
> +import {Gradient} from '@mui/icons-material'
done

2023-11-20 08:44 UTC, ctwhome commented on frontend/components/home/rsd/index.tsx
> +      <div className="max-w-screen-xl mx-auto p-5  grid lg:grid-cols-[1fr,1fr] gap-8 md:gap-20 md:my-28">
I would like to focus the attention on the left side, the video comes second. Especially since not all the users will click on play, but they can still read the title from the left side.

2023-11-20 08:48 UTC, ctwhome commented on frontend/components/home/rsd/index.tsx
> +    </div >
I think somethign when wrong with my formatter, hopefully I managed to make it work again. thanks for the observation!

2023-11-20 09:23 UTC, jmaassen approved these changes
Looks great!

2023-11-20 12:01 UTC, merged