fix: use docker compose extend to override frontend service settings …
research-software-directory/RSD-as-a-service pull request #1083
Opened 2024-01-09 16:04 UTC by cmeessen

## Fix undiscoverable frontend container in dev mode

Fixes #1082

Changes proposed in this pull request:

* use docker compose [extend](https://docs.docker.com/compose/multiple-compose-files/extends/#example-use-case) to override settings of the `frontend` service using a second compose file.

How to test:

* `make frontend-docker` and verify that the frontend runs in dev mode inside docker

PR Checklist:

*   [ ] Increase version numbers in `docker-compose.yml`
*   [x] Link to a GitHub issue
*   [ ] Update documentation
*   [ ] Tests

2024-01-09 19:07 UTC, dmijatovic commented
@cmeessen I did not notice this PR is still in draft mode. It looks good to me and I wanted to approve it :-)

2024-01-10 08:53 UTC, cmeessen commented
@dmijatovic thanks, I still wanted to update the documentation. It's done now and ready for review

2024-01-11 09:11 UTC, dmijatovic requested changes
Nice work. I have one suggestion about documentation. We want to use the documentation website for RSD users and README.md files in the repo for developers.

2024-01-11 09:11 UTC, dmijatovic commented on documentation/docs/03-rsd-instance/02-configurations.md
> +
Hm...maybe few more updates are needed in the root README.md. I see also Getting started link to old documentation website. Maybe we can make additional issue for updating main README file?

2024-01-11 09:27 UTC, cmeessen commented on documentation/docs/03-rsd-instance/02-configurations.md
> +
I did remove the comments in the documentation. If there is only that one link in the main README that you want to fix, I can also add that one. Or would you like to do more extensive checking?

2024-01-11 09:34 UTC, dmijatovic commented on documentation/docs/03-rsd-instance/02-configurations.md
> +
I think we can remove the link to getting started. That section does not exist in new documentation. And we already have a link to frontend readme file.

2024-01-11 09:42 UTC, dmijatovic approved these changes
Great improvement! Thanks.

2024-01-11 09:42 UTC, dmijatovic commented on docker-compose.dev.yml
> +    - ./deployment/rsd:/app/public
One more suggestion. Can you comment out line 21? This means that by default public folder in the frontend folder will be used by default.

2024-01-11 10:00 UTC, merged