1095 distinguish openid providers
research-software-directory/RSD-as-a-service pull request #1100
Opened 2024-01-26 12:17 UTC by cmeessen

# Distinguish between login and coupling auth providers

Fixes #1095 #1097 #1099

Changes proposed in this pull request:

* Distinguish between auth providers used for login and for account coupling. This allows couple an ORCID account to an RSD account without having to allow ORCID login simultaneously
* :exclamation: This PR splits the `RSD_AUTH_PROVIDERS` environment variable into `RSD_AUTH_LOGIN_PROVIDERS` and `RSD_AUTH_COUPLE_PROVIDERS`

How to test:

* in `.env`, set:
  ```
  RSD_AUTH_LOGIN_PROVIDERS="SURFCONEXT;LOCAL"
  RSD_AUTH_COUPLE_PROVIDERS=ORCID
  ```
* `docker compose build --parallel && docker compose up --scale scrapers=0`
* open login dialogue and verify that providers are Surf and Local only
* login
* navigate to user profile and link an ORCID account to the rsd account
* `docker compose down`
* add `ORCID` to `RSD_AUTH_LOGIN_PROVIDERS` and repeat previous steps. Verify that ORCID login works

PR Checklist:

*   [ ] Increase version numbers in `docker-compose.yml`
*   [ ] Link to a GitHub issue
*   [ ] Update documentation
*   [ ] Tests

2024-01-30 13:19 UTC, cmeessen commented
Waiting for #1103 to be closed by @ewan-escience

2024-02-07 13:53 UTC, ewan-escience requested changes
Looks good, just one small renaming needed.

2024-02-07 13:53 UTC, ewan-escience commented on authentication/src/main/java/nl/esciencecenter/rsd/authentication/Config.java
>  	private static Collection<String> rsdAuthProviders() {
I would rename this method to `rsdAuthCoupleProviders`

2024-02-07 13:55 UTC, ewan-escience commented
It is also good to note that when ORCID login is disabled and ORCID coupling is enabled, when an ORCID is coupled, this ORCID is still added to the login allow list.

2024-02-07 14:49 UTC, cmeessen commented on authentication/src/main/java/nl/esciencecenter/rsd/authentication/Config.java
>  	private static Collection<String> rsdAuthProviders() {
Good point, I updated this.

2024-02-07 14:50 UTC, cmeessen commented
> It is also good to note that when ORCID login is disabled and ORCID coupling is enabled, when an ORCID is coupled, this ORCID is still added to the login allow list.

I added a warning about this into the documentation, and also split it up into sections for common variables, coupling and authentication respectively. Could you please double check whether all common variables are mentioned correctly?

2024-02-07 15:02 UTC, ewan-escience commented
> Could you please double check whether all common variables are mentioned correctly?

Everything seems to be there. You used as example`ORCID_REDIRECT_COUPLE=http://YOUR-RSD-DOMAIN/auth/couple/orcid`, maybe you can also use `YOUR-RSD-DOMAIN` for `ORCID_REDIRECT`.

2024-02-08 09:11 UTC, dmijatovic commented on .env.example
> +RSD_AUTH_PROVIDERS="SURFCONEXT;ORCID;AZURE;LOCAL"
Do we need `"`? I think it works with or without `"` and we do not use in other variables.

2024-02-08 09:34 UTC, cmeessen commented on .env.example
> +RSD_AUTH_PROVIDERS="SURFCONEXT;ORCID;AZURE;LOCAL"
I think I added it because I had an issue with the `;` being interpreted as a command separator. But I couldn't reproduce it and removed the `"`.

2024-02-09 09:12 UTC, ewan-escience approved these changes

2024-02-09 09:54 UTC, merged