1170 dedicated highlights page
research-software-directory/RSD-as-a-service pull request #1171
Opened 2024-04-16 12:13 UTC by cmeessen

# Pull request Title

Fixes #1170

Changes proposed in this pull request:

*      

How to test:

*

PR Checklist:

*   [ ] Increase version numbers in `docker-compose.yml`
*   [ ] Link to a GitHub issue
*   [ ] Update documentation
*   [ ] Tests

2024-04-18 13:11 UTC, ewan-escience commented on frontend/pages/software/index.tsx
> +      limit: 3,
I don't know if this is what we want.

2024-04-19 11:55 UTC, dmijatovic commented
I made limit variable and added notification on the admin page.

![image](https://github.com/research-software-directory/RSD-as-a-service/assets/9204081/ef3574a7-bef6-42d5-956c-e998cbe327ac)

@cmeessen, @jmaassen and @ewan-escience Can you validate please?

2024-04-19 11:56 UTC, dmijatovic approved these changes

2024-04-19 11:58 UTC, dmijatovic commented on documentation/docs/03-rsd-instance/03-administration.md
> +      "description": "Descriptive text below page headline."
I forgot to update documentation with limit parameter :-(.

2024-04-19 12:52 UTC, ewan-escience requested changes
One typo, otherwise nice work.

2024-04-19 12:52 UTC, ewan-escience commented on documentation/docs/03-rsd-instance/03-administration.md
> +You can customise the software highlights section title in `settings.json` by providing a values for the optional property `software_highlights`:
`a values` is wrong

2024-04-19 14:34 UTC, dmijatovic commented on documentation/docs/03-rsd-instance/03-administration.md
> +      "description": "Descriptive text below page headline."
I updated the documentation. Please double check.

2024-04-22 13:00 UTC, ewan-escience approved these changes

2024-04-24 10:06 UTC, jmaassen commented
Works well, so go ahead and merge. 

Some point for improvement at a later time: 

- It would indeed be more convenient to always add the new highlights at the top position
- On the "all software highlights" page, the default order is "newest first" which implies a chronological order. There is no timestamp of any kind on the highlight cards however? Do we want this? 
- When adding highlights, the search bar also shows results that are already highlighted. Adding them again gives an error. We should either not show these in the search result, or alternatively, adding them again means moving them to the top spot again?

2024-04-24 10:06 UTC, jmaassen approved these changes

2024-04-25 08:03 UTC, merged