feat: admins can set parent organisation
research-software-directory/RSD-as-a-service pull request #1178
Opened 2024-04-23 07:15 UTC by cmeessen

# Admins can set parent organisation in frontend

Closes #1177 

Changes proposed in this pull request:

* adds a feature for administrators to be able to set the parent organisation of an organisation
* visually separates the block with administrator settings under "General settings" 

![image](https://github.com/research-software-directory/RSD-as-a-service/assets/14222414/b0840890-4488-40e5-ac81-a906649b3398)

How to test:

* `docker compose build --parallel && docker compose up --scale scrapers=0`
* `docker compose run data-generation`
* login as administrator
* open an organisation page and navigate to settings
* copy the organisation id from within the admin panel\
* open another organisation's settings and paste the organisation id into the "Parent organisation ID" field
* verify that the organisation is now a child of the other organisation
* alter the organisation id so that it is invalid => error is shown
* remove the parent organisation id and verify that the organisation is now not a child organisation anymore

PR Checklist:

*   [ ] Increase version numbers in `docker-compose.yml`
*   [x] Link to a GitHub issue
*   [ ] Update documentation
*   [ ] Tests

2024-04-23 08:19 UTC, dmijatovic commented on frontend/components/organisation/settings/general/RsdAdminSection.tsx
>        <ControlledSwitch
Maybe put ControlledSwitch next to parent (move it into the section and the grid layout should take care of positioning)?

2024-04-23 08:21 UTC, dmijatovic commented on frontend/components/organisation/settings/general/RsdAdminSection.tsx
> +      <h3 className='pb-4'>Admin section</h3>
Maybe label it as RSD admin section? The settings are shown to organisation admin/maintainers

2024-04-23 08:29 UTC, dmijatovic commented on frontend/components/organisation/settings/general/RsdAdminSection.tsx
> +    <section className='p-2 border-warning border-2'>
Please remove warning border. I think the section is clearly defined with the title and spacing (maybe add more space)

2024-04-23 08:45 UTC, dmijatovic commented
One general remark. Changing the slug or the parent will completely break the organisation page (404). I think it will be more suitable to move complete rsd admin section to rsd admin pages. I am curious to here what others think.

2024-04-23 10:37 UTC, cmeessen commented on frontend/components/organisation/settings/general/RsdAdminSection.tsx
>        <ControlledSwitch
I put it next to the organisation id, because the switch did not properly align vertically with the input box of the parent id.

2024-04-23 10:37 UTC, cmeessen commented on frontend/components/organisation/settings/general/RsdAdminSection.tsx
> +    <section className='p-2 border-warning border-2'>
Done

2024-04-23 10:38 UTC, cmeessen commented on frontend/components/organisation/settings/general/RsdAdminSection.tsx
> +      <h3 className='pb-4'>Admin section</h3>
From my perspective "Admin section" is clear enough, as there currently is only one admin role for the RSD.

2024-04-23 11:01 UTC, dmijatovic commented on frontend/components/organisation/settings/general/RsdAdminSection.tsx
> +      <h3 className='pb-4'>Admin section</h3>
OK. I confused it with the organisation admin role, but the term we use is "maintainer". So the terminology might be sufficient.

2024-04-23 11:15 UTC, cmeessen commented
> One general remark. Changing the slug or the parent value will completely break the organisation page (404). This is solved on edit software slug page (see ...software/edit/information/AutosaveSoftwareTextField.tsx, line 55).

The page is now reloaded using the correct slug.

> Maybe is more suitable to move the complete rsd admin section to rsd admin pages and extend editing the organisation props there? The other location could be parent organisation/add research unit?

That could potentially make sense, however as there were already fields that could only be set by admins I found it the most straight forward way to also set the parent here.

2024-04-23 11:38 UTC, dmijatovic commented on frontend/components/organisation/settings/general/AutosaveOrganisationTextField.tsx
> +      if (name === 'parent') {
The slug has same problem, can you extend logic to 
```javascript
if (name === 'parent' || name === 'slug') {...}
```

2024-04-23 11:39 UTC, dmijatovic commented on frontend/components/organisation/settings/general/AutosaveOrganisationTextField.tsx
> +          router.push(`/organisations/${updatedSlug}?tab=settings&settings=general`)
We can keep the scroll pposition so the page does not jumps at reload. I would do it like this
```Javascript
const url = `/organisations/${updatedSlug}?tab=settings&settings=general`
// keep the scroll position
router.push(url,url,{scroll:false})
```

2024-04-24 08:57 UTC, cmeessen commented on frontend/components/organisation/settings/general/AutosaveOrganisationTextField.tsx
> +      if (name === 'parent') {
Done

2024-04-24 08:57 UTC, cmeessen commented on frontend/components/organisation/settings/general/AutosaveOrganisationTextField.tsx
> +          router.push(`/organisations/${updatedSlug}?tab=settings&settings=general`)
Done!

2024-04-24 09:15 UTC, cmeessen commented
Ready to merge from my point of view

2024-04-24 10:03 UTC, dmijatovic commented on frontend/components/organisation/settings/general/AutosaveOrganisationTextField.tsx
> +          router.push(url, url, {scroll: false})
Should this be newUrl?

2024-04-24 10:41 UTC, jmaassen commented
When I set or unset the parent ID and leave the focus of the parentID field I get redirected to an API endpoint? 

For example, whet I create two organizations in an empty RSD (using ROR [00rbjv475](https://ror.org/00rbjv475) and [037aan677](https://ror.org/037aan677)): 

![Screenshot 2024-04-24 at 12-36-58 Organisations Admin page Research Software Directory](https://github.com/research-software-directory/RSD-as-a-service/assets/1705533/9d433462-5778-480f-ba44-3f1b22202f32)

And then copy the ID of NL eScience and set it as parent ID of NZ eScience: 

![Screenshot_2024-04-24_12-37-23](https://github.com/research-software-directory/RSD-as-a-service/assets/1705533/982f8312-38ba-410b-a3f7-7fa7d380be0a)

Then when leaving the ParentID field, the next screen I get is this: 

![Screenshot_2024-04-24_12-40-55](https://github.com/research-software-directory/RSD-as-a-service/assets/1705533/656f3fb0-c4c4-45a1-ab3c-d86232267793)

Is that the expected behavior? (I'm on firefox by the way).

2024-04-24 12:30 UTC, ewan-escience requested changes
I have the same issue as Jason. Furthermore, SonarCloud suggests to remove some unused imports. Otherwise, nice feature!

2024-04-25 08:33 UTC, cmeessen commented
Apologies, @dmijatovic was right, there was a typo with the url variable. I fixed it and it works now.

2024-04-25 12:26 UTC, ewan-escience commented on frontend/components/organisation/settings/general/AutosaveOrganisationTextField.tsx
> +import {createJsonHeaders, extractReturnMessage} from '~/utils/fetchHelpers'
These imports are unused.

2024-04-25 13:57 UTC, cmeessen commented on frontend/components/organisation/settings/general/AutosaveOrganisationTextField.tsx
> +import {createJsonHeaders, extractReturnMessage} from '~/utils/fetchHelpers'
Thank you for your patience, I removed it

2024-04-25 13:58 UTC, ewan-escience approved these changes

2024-04-25 16:13 UTC, dmijatovic approved these changes
Nice work!

2024-04-26 07:02 UTC, jmaassen approved these changes
Works great!

2024-04-26 07:22 UTC, merged