1222 my communities
research-software-directory/RSD-as-a-service pull request #1229
Opened 2024-06-18 13:44 UTC by dmijatovic

# Add my communities to user section

Closes #1222

Changes proposed in this pull request:
* My communities added to user menu option if communities module enabled in settings.json
* Communities page added to users section. It uses community list layout
* My software page updated to use software list items
* My projects page updated to use project list items
* My organisations page uses organisation list (new component created)
* Project metadata page moved lover in the user menu (on the right side of page)
   
How to test:
* enable communities module in frontend/public/data/settings.json
```json
{
  "host":{
     ...
     "modules":["software","projects","organisations","communities"]
   }
   ...
}
```
* `make start` to build app and generate test data 
* login as rsd admin (first user is by default admin in dev)
* navigate to software overview, select software, edit software. Navigate to maintainers section, create link and copy/pate link in the address-bar to become maintainer of this software. Add yourself as maintainer to few other software entries
* navigate to projects overview, select project, edit project. Add yourself as maintainer using invite link (as you did with software)
* navigate to organisations overview, select organisation. Navigate to settings and invite yourself to be maintainer. Do this with few organisations. 
* navigate to communities overview, select community. Navigate to settings and invite yourself as maintainer. Do this with multiple communities. 

## Example my software

## Example my projects

## Example my organisations

## Example my communities

PR Checklist:

*   [ ] Increase version numbers in `docker-compose.yml`
*   [x] Link to a GitHub issue
*   [ ] Update documentation
*   [x] Tests

2024-06-19 12:50 UTC, ewan-escience requested changes
Nice work! I have one comment in the code and the following suggestion:

The number of rows shown are not saved, maybe you can reuse the cookie value of `rsd_page_rows`?

2024-06-19 12:50 UTC, ewan-escience commented on frontend/components/user/communities/useUserCommunities.tsx
> +      url += `&name=ilike.*${searchFor}*`
Please URL encode `searchFor`, also in other places where applicable.

2024-06-21 07:34 UTC, jmaassen commented
For projects, organizations and communities, the list view also shows the image, but for software it does not?

2024-06-21 10:11 UTC, dmijatovic commented
@jmaassen Well spotted. It is fixed now. Can you approve. please?

2024-06-24 09:41 UTC, ewan-escience approved these changes
On "My communities", the counts sometimes show as `0–0 of 0`, but this will be fixed soon.

2024-06-24 09:42 UTC, merged