feat: provide eduperson_entitlements in user token
research-software-directory/RSD-as-a-service pull request #1303
Opened 2024-09-20 09:01 UTC by cmeessen

# Pull request Title

Fixes #

Changes proposed in this pull request:

*      

How to test:

*

PR Checklist:

*   [ ] Increase version numbers in `docker-compose.yml`
*   [ ] Link to a GitHub issue
*   [ ] Update documentation
*   [ ] Tests

2024-09-27 11:51 UTC, dmijatovic commented on documentation/docs/03-rsd-instance/05-plugins.md
> +# Configuring Plugins
Can you change h1 title to Plugins? I believe this should match file name in order to use it as label in the menu.

2024-09-27 11:57 UTC, dmijatovic commented on documentation/docs/03-rsd-instance/05-plugins.md
> +
Can you remove license header from md file and create separate license file (as with other md files)? 
The license header seem to confuse docusaurus so it cannot use h1 as menu option.

2024-09-27 11:58 UTC, dmijatovic commented on documentation/docs/04-contribute/06-plugin-development.md
> +-->
Can you remove license header from md file and create separate license file (as with other md files)? 
The license header seem to confuse docusaurus so it cannot use h1 as menu option.

2024-09-27 11:59 UTC, dmijatovic commented on documentation/docs/03-rsd-instance/05-plugins.md
> +# Configuring Plugins
Maybe just use Plugins as main title?

2024-09-27 13:25 UTC, dmijatovic reviewed
Nice work! 
I have some improvement suggestions. Let's discuss how and when to implement these.

2024-09-27 13:25 UTC, dmijatovic commented on frontend/utils/userPlugins.ts
> +import {PluginSlot} from '~/config/RsdPluginContext'
Looking at the endpoint we use to get information is called `config` I would prefer type to be called `PluginConfig` instead of PluginSlot. 

Another naming suggestion is use of route `modules`, maybe we can use `plugins` instead?
The url blueprint in this case would be `/plugins/{pluginName}/config`

I am curious to hear what the rest of the team thinks.

2024-09-27 13:25 UTC, dmijatovic commented on frontend/utils/userPlugins.ts
> +  return pluginSlots.flat()
I think we should extend pluginSlots array to include plugin name information (so the array can be filtered by plugin if needed). 

I am also not sure that flat() method will produce expected results when more that one plugin is present. 
I would like to think more about the changes I would like to add to this method.

2024-09-30 13:14 UTC, dmijatovic approved these changes
Nice team work!
Now let other perform double check, especially documentation.

2024-10-02 14:42 UTC, ewan-escience requested changes
I'm requesting changes here to prevent this PR fro being merged while not being ready. First, #1310 should be improved upon and merged into this branch, resolving the issue that the plugins are not reachable from the Next.js server when running the frontend in prod mode (i.e. built in Docker).

2024-10-07 07:52 UTC, dmijatovic commented on frontend/config/getPlugins.ts
> +  const url = getPluginBaseUrl(pluginName) + '/api/v1/config'
Maybe move  `/api/v1/config` into getPluginUrl and use it only in elseif cases?

2024-10-07 07:53 UTC, dmijatovic approved these changes

2024-10-07 08:50 UTC, dmijatovic commented on frontend/config/getPlugins.ts
> +    const baseUrl = process.env.RSD_REVERSE_PROXY_URL
Maybe we can add default `http://nginx`?

```javascript
const baseUrl = process.env.RSD_REVERSE_PROXY_URL ?? 'http://nginx'
```

2024-10-07 10:10 UTC, ewan-escience approved these changes

2024-10-07 10:53 UTC, merged