1294 categories for projects organisations
research-software-directory/RSD-as-a-service pull request #1315
Opened 2024-10-08 19:22 UTC by dmijatovic

# Categories for organisations

Closes #1294

Changes proposed in this pull request:

*      

How to test:

*

PR Checklist:

*   [ ] Increase version numbers in `docker-compose.yml`
*   [ ] Link to a GitHub issue
*   [ ] Update documentation
*   [ ] Tests

2024-10-15 09:08 UTC, jmaassen commented
I seem to have run into a bug. This are the steps I took

- create an empty RSD
- created an organization "Netherlands eScience Center"
- added category "Calls" with subcategories "ASDI2018, ASDI2020, ETEC2020, KD2019"
- added category "Expertise" with subcategory "Computing" and subsubcategories "GPU, Low power, distributed" 
- added to category "Expertise" subcategory "Big data" and subsubcategories "Real time, Heterogeneous" 

Next added project: 

- test
- organization: "Netherlands eScience Center"
- categories: Calls/ASDI2018, Expertise: Computing/GPU and Big Data/Real Time
- publish project

Project page of "test" looks as expected

Next added another project: 

- test2
- organization: "Netherlands eScience Center"
- categories: Calls/ETEC2020, Expertise: Computing/Low Power and Big Data/Heterogeneous
- publish project

Project page of "test2" looks as expected

But the categories of project "test" have now disappeared?

2024-10-15 16:16 UTC, dmijatovic commented
@jmaassen Well spotted! I have fixed bug. The PR is (again) ready for testing.

2024-10-16 11:02 UTC, ewan-escience reviewed
I will adapt/edit the row level security rules for the tables.

2024-10-16 13:32 UTC, ewan-escience requested changes
When adding a new non-root category to an organisation, the two switches to enable/disable software and/or projects for this category is visible, untill you type something in one of the input fields.

Otherwise, nice work!

2024-10-16 13:32 UTC, ewan-escience commented on frontend/types/Category.ts
> -export type CategoryID = string // NOSONAR ignore: typescript:S6564
I think the idea of this type is that you can later make the type more specific than it just being a string (like a UUID). Removing it now will make it harder to re-add it later on.

2024-10-17 09:45 UTC, dmijatovic commented on frontend/types/Category.ts
> -export type CategoryID = string // NOSONAR ignore: typescript:S6564
Let's do this when the time comes

2024-10-17 09:55 UTC, dmijatovic commented
@jmaassen I fixed the modal error Ewan noticed. Can you test again?

2024-10-17 09:55 UTC, ewan-escience approved these changes

2024-10-17 15:14 UTC, ewan-escience approved these changes

2024-10-18 07:44 UTC, jmaassen commented
The issue is gone now, and everything works as expected.

2024-10-18 08:01 UTC, jmaassen approved these changes

2024-10-24 10:39 UTC, merged