fix: remote markdown url validation and suggestions
research-software-directory/RSD-as-a-service pull request #1322
Opened 2024-10-18 13:31 UTC by dmijatovic

# Improve remote markdown detection

Closes #494

Changes proposed in this pull request:
* RSD api endpoint created to avoid CORS problem
* If provided url returns html page we raise an error and suggest raw markdown url (for Github and Gitlab this will work properly)

How to test:
* `make start` to build and generate test data
* login as rsd admin and edit existing software or create new.
* try remote markdown with following urls:
   * https://github.com/research-software-directory/RSD-as-a-service/blob/main/README.md
   * https://raw.githubusercontent.com/research-software-directory/RSD-as-a-service/refs/heads/main/README.md
   * https://gitlab.com/dmijatovic/nexter-demo/-/blob/master/README.md?ref_type=heads
   * https://gitlab.com/dmijatovic/nexter-demo/-/raw/master/README.md?ref_type=heads
   * https://bitbucket.org/dmijatovic/publictest/src/main/README.md
   * https://bitbucket.org/dmijatovic/publictest/raw/85e8651f290d058ad7832d09efa2fd63873b648b/README.md
   * 

PR Checklist:

*   [ ] Increase version numbers in `docker-compose.yml`
*   [ ] Link to a GitHub issue
*   [ ] Update documentation
*   [ ] Tests

2024-10-21 15:05 UTC, ewan-escience reviewed
The GitHub example works nicely, but why don't the GitLab ones generate a suggestion?

2024-10-22 07:54 UTC, jmaassen approved these changes
Works great! This is a really useful improvement

2024-10-22 11:50 UTC, ewan-escience approved these changes

2024-10-23 08:03 UTC, ewan-escience requested changes
I can indeed recreate the bug Jason experiences (ecept that it does stay at Markdown URL). The updated URL only gets saved when after the suggestion is applied, you click in and outside of the URL field.

2024-10-24 09:43 UTC, dmijatovic commented
@jmaassen Well spotted! I have fixed the bug, please check again.

2024-10-24 10:54 UTC, ewan-escience approved these changes

2024-10-25 07:57 UTC, jmaassen commented
Works as expected now. However, I did get the following while testing: 

![Screenshot 2024-10-25 at 09-49-43 Edit software Research Software Directory](https://github.com/user-attachments/assets/43241f92-7d0a-46f1-a6db-f035d225c8af)

Unfortunately, I cannot reproduce this a second time? 

I tested the bitbucket URL replacement first, followed by the helmholtz one. The markdown loaded as expected, but the error was also shown. When clicking "view software" the description reverted to the bitbucket example. Adding the helmholtz one a second time did work, and after that I could not reproduce the error.

2024-10-28 10:28 UTC, dmijatovic commented
@jmaassen I cannot reproduce the error. Shell we merge this PR as it is?

2024-10-28 12:07 UTC, merged