1287 remote rsd search
research-software-directory/RSD-as-a-service pull request #1356
Opened 2024-11-28 16:49 UTC by dmijatovic

# Search for software in multiple RSD instances

Closes #1287

Changes proposed in this pull request:
* rsd admin can add remote RSD to be included in software search on software overview page
*      

How to test:
* `make start` to build and generate test data
* 

PR Checklist:

*   [ ] Increase version numbers in `docker-compose.yml`
*   [ ] Link to a GitHub issue
*   [ ] Update documentation
*   [ ] Tests

2024-12-09 10:22 UTC, jmaassen commented
The fetching of the remote RSD name seems to be a bit buggy?

When I add the dev server URL, the remote RSD name does not show up automatically. Instead I have to click the "remote control icon" first. Why not fetch it and allow the admin to change it later?

![Screenshot_2024-12-09_11-02-57](https://github.com/user-attachments/assets/f565e478-9530-4e10-aa3e-c15a1d694642)

After fetching the name, the text box containing it seems messed up? Also, the save icon is still disabled.

![Screenshot_2024-12-09_11-02-16](https://github.com/user-attachments/assets/775a9f3f-1ee9-4eac-ab35-7d0d61999892)

When clicking on the name text box, it is cleaned up, but the save is still disabled. 

![Screenshot_2024-12-09_11-03-51](https://github.com/user-attachments/assets/3a165dbb-4f88-472f-8fdf-886304a8b445)

Clicking on the update interval or URL box activates the save button.

2024-12-09 10:44 UTC, jmaassen commented
When selecting by keyword, the selected keyword does not always show up. For example, when harvesting from the RSD SAAS and Helmholtz RSD, selecting "3D" works as expected: 

![Screenshot 2024-12-09 at 11-37-49 Software Research Software Directory](https://github.com/user-attachments/assets/1a7d8fbe-b73a-4568-987d-0e0f419052d3)

However, if I select "Data Analysis" instead, the filter works as expected, but isn't shown in the sidebar:

![Screenshot 2024-12-09 at 11-36-37 Software Research Software Directory](https://github.com/user-attachments/assets/2d1eeead-9205-46d0-a8f5-16d51f0a980a)

All others I've tried seem to work as expected, so I'm not sure what the problem is with this one?

2024-12-09 16:30 UTC, dmijatovic commented
@jmaassen Well spotted! I have fixed both remarks. I did force push so please remote old branch and pull again.

2025-01-10 10:40 UTC, cmeessen commented
When adding research-software.dev as a remote I get this error message:

![grafik](https://github.com/user-attachments/assets/fe5eb038-cc3f-4e8d-95be-af9252317f19)

2025-01-10 12:44 UTC, ewan-escience commented on database/025-rsd-info.sql
> +INSERT INTO rsd_info VALUES
We don't use these, I would remove them, even the `remote_name` key.

2025-01-10 12:56 UTC, cmeessen commented
Using the global search does not include the results from remote RSDs.

2025-01-13 10:01 UTC, jmaassen commented
When looking at the NWO website, I noticed that they used the following method for indicating that clicking on a tile leads to an external website: 

![Screenshot 2025-01-13 at 10-58-24 Klimaatonderzoek NWO](https://github.com/user-attachments/assets/51c706ce-7569-4991-890d-62c8bdcd0927)

So a similar "exit" icon that we discussed during out meeting last friday.

2025-01-20 10:43 UTC, dmijatovic commented
@jmaassen, @cmeessen This PR is ready for next round of tests. 

- Remote software is included in global search. Some ui changes are made to indicate origin of the software
- The UI of cards and the list is adapted to more clearly indicate "remote" software and opening of new tab

2025-01-21 14:23 UTC, ewan-escience requested changes
1. When there are no entires in `rsd_info` (because they were directly deleted in the database), the Add button is not there.
1. I would also make the `remote_name` entry fully mutable (don't disable the slider and delete button).
1. The database enforces the `label` of `remote_rsd` to be of at least length 3, but the frontend form doesn't show this.
1. The software overview page doesn't handle a missing `remote_name` gracefully: it shows a blank entry in the filter and when you click on it, it shows nothing with a `null` in the URL bar in the `sources` parameter.

2025-01-21 14:23 UTC, ewan-escience commented on database/025-rsd-info.sql
> +-- EXAMPLE OF PUBLIC PROPERTIES TO INSERT IN THE rsd_info table
I would remove this entry and add it to the data generation.

2025-01-21 14:23 UTC, ewan-escience commented on deployment/docker-compose.yml
> -# SPDX-FileCopyrightText: 2023 Dusan Mijatovic (Netherlands eScience Center)
Not a blocker, but these copyright updates should be undone. (Also in the global `docker-compose.yml`.)

2025-01-21 14:23 UTC, ewan-escience commented on documentation/docs/03-rsd-instance/01-getting-started.md
> +- Define remote name of your instance in the .env file. Other RSD instances can pull software information from your instance. How to link the remote RSD instances is described in the [remotes chapter
This should be removed.

2025-01-21 14:23 UTC, ewan-escience commented on documentation/docs/03-rsd-instance/03-administration.md
> +When connecting to remote RSD instances, each software card in the software overview shows the source RSD. The software from the "local" RSD uses `remote_name` from the rsd_info table. This value is
This should be removed.

2025-01-22 09:45 UTC, jmaassen commented
The new tab to add RSD info has different capitalization from the others. It uses "Rsd" instead of "RSD":  

![Screenshot 2025-01-22 at 10-38-49 Rsd info Admin page Research Software Directory](https://github.com/user-attachments/assets/6b1c551a-1566-4c04-b78b-b1c99b2e9135)

2025-01-22 10:16 UTC, jmaassen commented
During testing of the RSD info tab, I somehow lost the rights to add key value pairs: 

![Screenshot 2025-01-22 at 11-08-02 Rsd info Admin page Research Software Directory](https://github.com/user-attachments/assets/3cc98729-fe18-431b-9ccc-65ecd615ca81)

results in: 

![Screenshot 2025-01-22 at 11-08-11 Rsd info Admin page Research Software Directory](https://github.com/user-attachments/assets/91a41e3b-a728-409b-842c-593ac4886ffa)

This could only be resolved by signing out and signing in again. 

I cannot reproduce this behavior however....

2025-01-22 10:33 UTC, jmaassen commented
When I change a value in the RSD info tab, while it it red, it appears to be stored but isn't. 

I start with a valid value: 

![Screenshot 2025-01-22 at 11-23-58 Rsd info Admin page Research Software Directory](https://github.com/user-attachments/assets/6a3b6a56-5cc8-47b3-9c65-2b6f8909e99e)

Then select and delete it: 

![Screenshot_2025-01-22_11-24-05](https://github.com/user-attachments/assets/a8027b68-bd94-4318-8315-fb84e162fb1c)

The value is restored:

![Screenshot 2025-01-22 at 11-23-58 Rsd info Admin page Research Software Directory](https://github.com/user-attachments/assets/71655a77-d467-4e2d-9e87-a725b5a19feb)

When I click it, the value turns read. I change it: 

![Screenshot_2025-01-22_11-24-38](https://github.com/user-attachments/assets/4760f514-c675-4576-9c6a-4cc8136b87cf)

The value seems stored:

![Screenshot 2025-01-22 at 11-25-51 Rsd info Admin page Research Software Directory](https://github.com/user-attachments/assets/42e16f08-23b3-41f6-951f-8f358ad7ee1f)

However, when I click and delete it again, the original value is restored, not the changed one:

![Screenshot_2025-01-22_11-25-59](https://github.com/user-attachments/assets/0c7b8e58-d275-426f-a19c-5e28b431d9b3)
![Screenshot_2025-01-22_11-26-09](https://github.com/user-attachments/assets/3dd3485f-3ef2-49bf-aa5a-8b96422b06da)
![Screenshot 2025-01-22 at 11-32-14 Rsd info Admin page Research Software Directory](https://github.com/user-attachments/assets/39a488ed-d2be-44eb-b3dd-3fab2036fb4a)

2025-01-22 13:47 UTC, jmaassen commented
The technical documentation for the RSD info tab is still missing I think?

2025-01-23 13:28 UTC, dmijatovic commented on database/025-rsd-info.sql
> +-- EXAMPLE OF PUBLIC PROPERTIES TO INSERT IN THE rsd_info table
I believe it is useful to have default value inserted. It serves as an example and the admin can change it.

2025-01-24 13:03 UTC, dmijatovic commented
@jmaassen, @cmeessen I have updated cards to use domain instead of remote name. If we like this I would also need to make further changes in definitions and for the drop-down filter.

2025-01-27 13:48 UTC, jmaassen commented
When adding a remote manually, the name is suggested as soon as one stops typing (or isn't typing fast enough). This name isn't changed after this:

![Screenshot 2025-01-27 at 14-45-59 Remotes Admin page Research Software Directory](https://github.com/user-attachments/assets/4e2211d7-60cd-4e22-8f43-91368f60db14)

It may make more sense to wait until the focus is lost in the URL entry field?

2025-01-27 14:14 UTC, jmaassen commented
In the global search, the default is to add @localhost to all overview pages: 

![Screenshot_2025-01-27_15-11-39](https://github.com/user-attachments/assets/b8b61b5b-d9ce-4456-a6c0-b14d441283b3)

However, these pages are always on the local RSD, so showing their name isn't needed?

2025-01-27 14:18 UTC, jmaassen commented
When adding remotes, the default timeout should be something not too aggressive, like 60 minutes+ or so.

2025-01-27 14:25 UTC, jmaassen approved these changes
Few small issues left, but we decided to move these to a separate issue and PR

2025-01-27 16:48 UTC, dmijatovic commented
@jmaassen I fixed remote name suggestion and increased default refresh rate to 60 min. I moved global search suggestion to new issue #1377

2025-01-28 13:55 UTC, merged