Add Helmholtz AAI as additional login provider
research-software-directory/RSD-as-a-service pull request #231
Opened 2022-04-20 11:02 UTC by ruester

# Add Helmholtz AAI as additional login provider

Please have a look at my changes to integrate the Helmholtz AAI as an alternative login provider for the RSD.
We also need a solution to let the user select the IdP when clicking on "Sign In" (currently it goes directly to SURFconext). Or maybe make it configurable in the frontend (via env variable?) which is the default login provider...

Fixes https://github.com/research-software-directory/Helmholtz/issues/3

Changes proposed in this pull request:

* add possibility to log in with Helmholtz AAI
* a more general approach for handling login providers in the frontend and backend
* using an additional library for handling the OAuth login and querying the userinfo endpoint
* add unit tests to the authentication backend module
* run tests for scrapers when building the docker image

How to test:

* fill in OAuth client secret for Helmholtz AAI
* run the JUnit and Jest tests by building the docker images
* go to frontend website `localhost/login`, click on Helmholtz AAI logo and log in

PR Checklist:

*   [ ] Increase version numbers in `docker-compose.yml`
*   [ ] Link to a GitHub issue
*   [ ] Update documentation
*   [ ] Tests

2022-04-20 19:36 UTC, ctwhome commented
Hi! I'll put back the menu selection when clicking on login, it is a modal window with different choices. Thanks for the PR

2022-04-21 08:06 UTC, ewan-escience commented on authentication/src/main/java/nl/esciencecenter/rsd/authentication/HelmholtzAaiLogin.java
> +				ent.matches("urn\\:geant\\:helmholtz\\.de\\:group.*")
My IDE says that the escape characters in front of the colons are not needed. Can you check this?

2022-04-21 08:07 UTC, ewan-escience commented on authentication/src/main/java/nl/esciencecenter/rsd/authentication/HelmholtzAaiLogin.java
> +				response.body().toString()
`toString()` is redundant

2022-04-21 08:08 UTC, ewan-escience commented on authentication/src/test/java/nl/esciencecenter/rsd/authentication/HelmholtzAaiLoginTest.java
> +import net.minidev.json.JSONArray;
Consider using gson instead.

2022-04-21 08:26 UTC, ewan-escience commented on scrapers/pom.xml
> +			<artifactId>junit-platform-launcher</artifactId>
No code was changed in this module, so why do we suddenly need this?

2022-04-21 08:26 UTC, ewan-escience commented on scrapers/pom.xml
> +			<artifactId>surefire-junit-platform</artifactId>
No code was changed in this module, so why do we suddenly need this?

2022-04-21 10:28 UTC, dmijatovic commented on frontend/utils/loginHelpers.ts
> +  const resp = await fetch(wellknownUrl)
This is sufficient for now. I think it will be more flexible to move most of the code to (next) api endpoint to return redirect url(s) to frontend directly, based on provided env variables which should include an list of providers to return. This approach needs further discussion about the requirements first, but should enable us to have 1 or more providers (if more than one provider defined in .env than some sort of provider selection should be shown to user). This is just a heads up for the future refactoring I expect we would need to implement.

2022-04-21 12:12 UTC, ruester commented on .env.example
> +NEXT_PUBLIC_HELMHOLTZAAI_SCOPES="openid+profile+email+eduperson_principal_name"
It's relevant also for the frontend as this must be included in the auth request send by the frontend. Helmholtz AAI needs those scopes so that the subsequent calls to the userinfo endpoint work. If we hardcode it in the frontend we also need to hardcode it in the backend so to keep it DRY I've implemented it at one place only and reused the env variable in the backend.

2022-04-21 12:15 UTC, ruester commented on authentication/pom.xml
> +				<artifactId>maven-failsafe-plugin</artifactId>
It was very difficult to find a valid combination of dependecies and plugins for JUnit to work. I've taken those from the pom.xml in the scrapers as Christian solved the JUnit issues there already.

2022-04-21 12:18 UTC, ruester commented on authentication/pom.xml
> +			<artifactId>oauth2-oidc-sdk</artifactId>
Yes, I've used this external library to reuse the logic the library offers. As I need to use the userinfo endpoint for the Helmholtz AAI to get mail, username and organisation.

I would argue that this is much safer in terms of security to use a external library for this instead of implementing the logic ourselves :sweat_smile: 
I think it is also the same repository/library/company the Helmholtz AAI itself is using internally.

2022-04-21 12:28 UTC, ruester commented on authentication/pom.xml
> +				<artifactId>maven-compiler-plugin</artifactId>
see https://github.com/research-software-directory/RSD-as-a-service/pull/231#discussion_r855120850

If you find another combination of dependencies that let JUnit work I am fine with a different solution.

If we use Java we are already in the dependency hell :wink: 
JUnit is a common library and it is not packed into the productive running jar, I guess. Otherwise we need to implement our own Testing framework, as test-driven development should be the way to go as far as it is possible and feasible :roll_eyes: 
RSD also uses libraries from `com.auth0` and `com.google.code.gson` which can also have security issues or disappear... In the case of this maven plugin we have to rely on maven not to disappear, but we already use it for building the Java classes..

2022-04-21 12:29 UTC, ruester commented on authentication/src/test/java/nl/esciencecenter/rsd/authentication/HelmholtzAaiLoginTest.java
> +import net.minidev.json.JSONArray;
JSONArray is returned from the OAuth library I am using. A conversion from this to gson did not work.

2022-04-21 12:30 UTC, ruester commented on scrapers/pom.xml
> +			<artifactId>junit-platform-launcher</artifactId>
See https://github.com/research-software-directory/RSD-as-a-service/pull/231#discussion_r855120850

2022-04-21 12:30 UTC, ruester commented on scrapers/pom.xml
> +			<artifactId>surefire-junit-platform</artifactId>
See https://github.com/research-software-directory/RSD-as-a-service/pull/231#discussion_r855120850

2022-04-21 14:30 UTC, ewan-escience commented on authentication/pom.xml
> +				<artifactId>maven-compiler-plugin</artifactId>
I don't think we're in dependency hell. We've managed to do fine with just a few dependencies. I'm just trying to keep the amount of dependencies low, but when needed it is of course fine to add them.

I'm not arguing we implement our own testing framework. Using JUnit is in fact my preferred way as well. I was just wondering if the listed set of dependencies is indeed the minimum we need, or if we can leave out some of them. What does the maven-compiler-plugin do for example?

2022-04-21 14:37 UTC, ewan-escience commented on scrapers/pom.xml
> +			<artifactId>junit-platform-launcher</artifactId>
But is was already working, right? What changed? Does the version upgrade of the maven-surefire-plugin and maven-failsafe-plugin dictate these dependencies?

2022-04-22 11:05 UTC, ruester commented on .env.example
> +NEXT_PUBLIC_SURFCONEXT_SCOPES="openid"
I've tested it, it works as expected... since this is sourced from the docker-compose there are no quotes in the actual value of the variable

2022-04-22 11:06 UTC, ruester commented on authentication/src/main/java/nl/esciencecenter/rsd/authentication/HelmholtzAaiLogin.java
> +				ent.matches("urn\\:geant\\:helmholtz\\.de\\:group.*")
only `.` needs to be escaped, fixed it now, thanks!

2022-04-22 11:08 UTC, ruester commented on authentication/src/main/java/nl/esciencecenter/rsd/authentication/HelmholtzAaiLogin.java
> +				response.body().toString()
removed it now, thanks :+1:

2022-04-22 11:14 UTC, ruester commented on scrapers/pom.xml
> +			<artifactId>junit-platform-launcher</artifactId>
Otherwise the docker build will fail as I added the testing to the docker build for the scrapers. Following error is shown if we do not add this dependency:

```
Step 7/18 : RUN mvn package --offline
...
[ERROR] Failed to execute goal on project scrapers: Could not resolve dependencies for
project nl.research-software:scrapers:jar:1.0-SNAPSHOT: Cannot access central
(https://repo.maven.apache.org/maven2) in offline mode and the artifact
org.junit.platform:junit-platform-launcher:jar:1.8.2 has not been downloaded from it before.
-> [Help 1]
...
```

So it mainly has something to do with the offline build I guess (?)

2022-04-22 11:24 UTC, ruester commented on authentication/pom.xml
> +				<artifactId>maven-compiler-plugin</artifactId>
I also want to use the bare minimum of dependencies, but for JUnit it was difficult to figure that out..
I've checked again the maven-compiler-plugin and it really seems not to be needed by JUnit and may be an old remaining of the many tries to get JUnit working... seems to be from the example repository at: https://github.com/junit-team/junit5-samples/blob/r5.8.2/junit5-jupiter-starter-maven/pom.xml 

I've removed that plugin now from authentication and scrapers

2022-04-22 11:27 UTC, ruester commented on scrapers/pom.xml
> +			<artifactId>surefire-junit-platform</artifactId>
If we omit it then this error appears:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.193 s
[INFO] Finished at: 2022-04-22T11:27:10Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M6:test (default-test) on project scrapers: Missing:
[ERROR] ----------
[ERROR] 1) org.apache.maven.surefire:surefire-junit-platform:jar:3.0.0-M6
[ERROR] 
[ERROR]   Try downloading the file manually from the project website.
[ERROR] 
[ERROR]   Then, install it using the command: 
[ERROR]       mvn install:install-file -DgroupId=org.apache.maven.surefire -DartifactId=surefire-junit-platform -Dversion=3.0.0-M6 -Dpackaging=jar -Dfile=/path/to/file
[ERROR] 
[ERROR]   Alternatively, if you host your own repository you can deploy the file there: 
[ERROR]       mvn deploy:deploy-file -DgroupId=org.apache.maven.surefire -DartifactId=surefire-junit-platform -Dversion=3.0.0-M6 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[ERROR] 
[ERROR] ----------
[ERROR] 1 required artifact is missing.
[ERROR] 
[ERROR] for artifact: 
[ERROR]   org.apache.maven.surefire:surefire-junit-platform:jar:3.0.0-M6
[ERROR] 
[ERROR] from the specified remote repositories:
[ERROR]   central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false)
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
```

2022-04-22 11:33 UTC, ruester commented on authentication/pom.xml
> +				<artifactId>maven-failsafe-plugin</artifactId>
As I only copied those plugins from the scrapers pom.xml I now tested it again and this plugin is also not needed for now... now removed :+1:

2022-04-22 11:47 UTC, ruester commented on .env.example
> +NEXT_PUBLIC_HELMHOLTZAAI_SCOPES="openid+profile+email+eduperson_principal_name"
I really have no other solution for now in the frontend without using environment variables here. Maybe this has something to with https://github.com/research-software-directory/RSD-as-a-service/pull/231#discussion_r855031916 ?

I could hardcode the providers in `getRedirectUrl` with something like:
```javascript
if (provider == 'surfconext') {
    scope = 'openid'
    response_mode = 'form_post'
}
if (provider == 'helmholtzaai') {
    scope = 'openid'
    response_mode = 'query'
}
```

But this is not extensible if another login provider will be added in the future. With the current solution you will "only" need 7 environment variables and the frontend login helper functions do not need to be touched. If the Helmholtz AAI changes the scopes in the future (imagine `eduperson_principal_name` being renamed to something else) we also do not need to touch any source code, but just change the environment variables...

2022-04-22 13:06 UTC, dmijatovic requested changes

2022-04-25 07:58 UTC, ruester commented on .env.example
> +NEXT_PUBLIC_SURFCONEXT_SCOPES="openid"
leaving the quotes should not break my "openid+email+..." values, so I think we can omit them, I will fix that :+1:

2022-04-25 08:58 UTC, ruester commented on authentication/pom.xml
> +			<artifactId>surefire-junit-platform</artifactId>
yes, we need this, at least AFAIK there is no other solution for now.. I've added the test scope both in authentication and scrapers pom.xml :+1:

2022-04-25 09:02 UTC, ruester commented on authentication/src/main/java/nl/esciencecenter/rsd/authentication/HelmholtzAaiLogin.java
> +import net.minidev.json.JSONArray;
I don't like it either, but would take it in exchange for the easiness of implementing the OAuth and Userinfo with that external library...
I removed that import :+1:

2022-04-25 09:28 UTC, ruester commented on authentication/src/main/java/nl/esciencecenter/rsd/authentication/HelmholtzAaiLogin.java
> +			e.printStackTrace();
removed :+1:

2022-04-25 09:31 UTC, ruester commented
We should squash the commits before merging as most of them are fixes for the PR and not fixes for the software.. Maybe only separate the changes for the authentication and scrapers module.

I was wondering if we maybe remove the changes of the frontend for this PR as you are already working on redesigning the configuration of login providers in a different PR. I would be fine with removing my changes to the frontend for now to avoid merge conflicts. The changes there were only for testing the authentication anyways...

2022-04-25 09:55 UTC, ewan-escience approved these changes
Thanks for your contributions. SURFconext login still works. I'm fine with squashing the commits that fix PR issues, if you can keep the essential commits.

2022-04-25 10:39 UTC, dmijatovic approved these changes

2022-04-25 12:56 UTC, merged