Styled AppHeader
research-software-directory/RSD-as-a-service pull request #309
Opened 2022-06-03 08:11 UTC by ctwhome

# Unified and styled App header

Fixes #307

<img width="1671" alt="image" src="https://user-images.githubusercontent.com/4195550/173667671-a263f9d3-13f6-464b-869f-3608dea9bc61.png">

Changes proposed in this pull request:

- [x] New app header styles and same as the landing page

This PR contains some code cleaning with a few files deleted for simplification

How to test:

* `make start`, and check that the app header is equal and behaves as it was before. 

PR Checklist:

*   [x] Increase version numbers in `docker-compose.yml`
*   [x] Link to a GitHub issue
*   [ ] Update documentation
*   [x] Tests

2022-06-15 13:58 UTC, dmijatovic commented on frontend/components/AppHeader/AddMenu.tsx
> -  }
Is this not useful validation? We allow add also when user is already on add software/add project page

2022-06-15 14:06 UTC, dmijatovic requested changes
Nice work. I have few minor remarks, posted in the code. In addition, it looks to me that font on the page links might be bit heavier (400 for example). The logo white color looks very bright while the menu options font color looks less bright/clear. Maybe it is my monitor? See pic below.

![image](https://user-images.githubusercontent.com/9204081/173847359-4de4f6fb-6f16-419e-a3b4-ce074f5bc9a5.png)

2022-06-15 14:06 UTC, dmijatovic commented on frontend/components/AppHeader/index.tsx
> +      className="z-10 px-5 md:px-10 bg-black text-white">
Maybe use `bg-secondary` from theme instead of `bg-black`? I would also add min height or just a height, like `h-[6rem]`. Currently the header height is different when you are logged in and not as the avatar increases the header height.

2022-06-17 09:41 UTC, dmijatovic approved these changes
Few remarks, but these can be handled later too.

2022-06-20 10:44 UTC, ctwhome commented
Added a responsive header and fixes the issues requested by @dmijatovic 

![](https://user-images.githubusercontent.com/4195550/174585259-5c1dc9f4-2e67-40ca-b357-57076cee87f7.gif)

2022-06-20 10:54 UTC, ctwhome commented on frontend/components/AppHeader/index.tsx
> +      className="z-10 px-5 md:px-10 bg-black text-white">
done thanks!

2022-06-20 11:07 UTC, ctwhome commented on frontend/components/AppHeader/index.tsx
> +      <div className="w-full max-w-screen-2xl mx-auto flex py-3 items-center">
yes, I overlooked that last time. Changed!

2022-06-20 11:07 UTC, ctwhome commented on frontend/components/AppHeader/index.tsx
> +      <div className="w-full max-w-screen-2xl mx-auto flex py-3 items-center">
yes, I overlooked that last time. Changed!

2022-06-20 11:09 UTC, merged