feat: enable custom theme,footer logo, contact email and custom links…
research-software-directory/RSD-as-a-service pull request #506
Opened 2022-09-05 18:55 UTC by dmijatovic

# Custom theme provider and settings.json

… using the settings.json. Custom settings can be uploaded using volume mounts.

# Pull request Title

Closes #359 
Closes #410 

Changes proposed in this pull request:
*      

How to test:

*

PR Checklist:

*   [ ] Increase version numbers in `docker-compose.yml`
*   [ ] Link to a GitHub issue
*   [ ] Update documentation
*   [ ] Tests

2022-09-05 19:09 UTC, dmijatovic commented
@ruester and @ctwhome I created new PR which is continuation of #410. Custom theme implementation. I will close #410 in favor of this new PR

2022-09-06 10:31 UTC, ruester commented on docker-compose.yml
> +    image: rsd/frontend:1.3.0
```suggestion
    image: rsd/frontend:1.4.0
```

2022-09-06 12:17 UTC, ruester commented
> create hmz folder in the deployment directory. Note I have added hmz folder in the .gitignore file

Is it planned that we add our custom theme to your repository (research-software-directory)? Or should we keep our customization in our hifis-net repository? If so the `.gitignore` in `/deployment` should be changed, so that it does not ignore the `hmz` directory. It makes it difficult for developers to commit their custom contents to the deployment directory (need to use `--force` when adding a file)...

2022-09-06 12:32 UTC, ruester commented on frontend/pages/index.tsx
> +  if (host && host.name.toLowerCase() === 'helmholtz') {
maybe this could be improved if you can set the component name dynamically like:

```react
if (host) {
  const compName = capitalize(host) + 'Home'
  <Component name="{compName}" />
}
```
pseudo-code due to missing react knowledge :sweat_smile: 
such a solution is possible in Vue (https://forum.vuejs.org/t/render-components-with-dynamic-names/14153/4), so I would assume this is also possible in React :wink: 

this way you would never have to touch this part of the index-component for other themes added in the future...

2022-09-06 12:34 UTC, dmijatovic commented
> Is it planned that we add our custom theme to your repository (research-software-directory)? Or should we keep our customization in our hifis-net repository?

@ruester I am open for suggestions. At this point I created description so you can replicate and test. If we agree that proposed approach covers all our needs then we can discuss location. I do prefer that our configuration is stored in the project repository as default. I assume that users who use RSD images (released RSD version) will mount their configuration in their production repo. If they do not mount any volumes our default configuration will be loaded (and RSD will work by default). 

In case of Helmholtz I am open for suggestions. Let me know what is your preference.

2022-09-06 12:48 UTC, ruester commented on frontend/pages/index.tsx
> +  if (host && host.name.toLowerCase() === 'helmholtz') {
so all future "home"-components need to have the same parameters.. so we do not use `{counts}` for now, but `HelmholtzHome` should be called with those props nevertheless

2022-09-06 13:07 UTC, ruester commented on frontend/styles/themeDefault.js
> -const colors = {
I cannot find a replacement for those color definitions, where are they now? Same with `themeConfig.js`, how are the primary or secondary colors are defined now?

2022-09-06 13:14 UTC, dmijatovic commented on frontend/styles/themeDefault.js
> -const colors = {
@ruester the themes and colors, along with other settings are defined in 'settings.json' (frontend/public/data/settings.json). Maybe is handy to plan an Teams session this or next week? You can join our daily standup at any time. Do you have a link?

2022-09-06 13:16 UTC, ruester commented on frontend/styles/themeDefault.js
> -const colors = {
ah, I think it is done now via CSS and the tailwind configuration using CSS vars?

2022-09-06 13:33 UTC, ruester commented on frontend/styles/themeDefault.js
> -const colors = {
@dmijatovic yes, good idea, I will join you on Thursday at 10:00, since I have another meeting tomorrow :+1:

2022-09-06 13:36 UTC, ruester commented
On first thought, I believe this breaks the development of the frontend since a `yarn dev` does not mount the custom theme... But I am still onto getting our customization into the new structure..

2022-09-06 13:45 UTC, ruester commented on frontend/styles/themeDefault.js
> -const colors = {
sorry, just found the `settings.json` which answers all my questions :wink: such a big PR :sweat_smile:

2022-09-07 06:58 UTC, ruester commented on frontend/pages/_document.tsx
> +  readonly fontFamily = process.env.RSD_FONT_HREF
this does not seem to be used in this file?

2022-09-07 06:59 UTC, ruester commented on frontend/pages/_app.tsx
> +  console.log('rsdSettings...', rsdSettings)
```suggestion
  // console.log('rsdSettings...', rsdSettings)
```

2022-09-07 07:37 UTC, ruester commented on frontend/pages/index.tsx
> +  const host = process.env.RSD_HOST ?? 'rsd'
this should be added/documented in the `.env.example` file too

2022-09-07 07:40 UTC, ruester commented on frontend/pages/index.tsx
> +  const host = process.env.RSD_HOST ?? 'rsd'
also this variable is not used in this file... I think it got replaced by configuring it in the `data/settings.json` file?

2022-09-07 08:03 UTC, ruester commented
I think I got it working now, see: https://github.com/hifis-net/RSD-as-a-service/tree/custom-themes
but maybe some things are not quite working as before, I will check...

2022-09-07 11:10 UTC, dmijatovic commented
> I think I got it working now, see: https://github.com/hifis-net/RSD-as-a-service/tree/custom-themes but maybe some things are not quite working as before, I will check...

@ruester Thanks for you feedback. I am working on bug issues at the moment. I will check your branch this Friday or Monday next week and come back with my feedback.

2022-09-08 08:30 UTC, ruester commented
For reference what we just have talked about, here is an example for having the `yarn dev` running within a docker container:
- https://github.com/locationtech/geoperil/blob/master/docker/docker-compose-dev.yml#L69
- https://github.com/locationtech/geoperil/blob/master/frontend/Dockerfile.dev
- https://github.com/locationtech/geoperil/blob/master/frontend/start-dev.sh

I will test to adopt this same behaviour for the RSD frontend, so that we can solve working with a custom theme in development mode.

2022-09-08 14:59 UTC, ruester commented
With my last commit I was able to have hot reload for the frontend with our custom theme mounted via docker-compose (see https://github.com/hifis-net/RSD-as-a-service/commit/db77ab1447f4f09203e6c9235af16282308b1478) :+1: 
I now have some problems with the organisation logos, but I will debug this too :wink: 
I also had to change the way the Helmholtz home page component is called (some additional props).. which diverged in our fork from the way the RSD home page component is called :confused: 
https://github.com/hifis-net/RSD-as-a-service/commit/c160343ccd9a8a16f563a6754bca6309a9734154
Maybe we can also find a generic solution to add a custom home page component so that it does not need to be commited in the RSD repository? :thinking:

2022-09-09 06:33 UTC, ruester commented
I've now updated the "How to test" section for this PR because with the new approach the directories `frontend/{node_modules,.next}` will be created by the `root` user and could lead to errors if those directories have mixed ownership

2022-09-09 07:28 UTC, ruester commented on nginx/nginx.conf
> +server {
I needed to serve the development mode of the frontend with nginx, so that all the other paths work too, because the frontend calls `localhost:3000/images` for example

2022-09-09 08:04 UTC, ruester commented
So all in all I got it working for our Helmholtz theme and home page. We may need to further implement generic approaches for the home page components, so that we end up with less merge conflicts over time, but this can be done later with some new issues/PRs.
Only some small remarks are left now from my side and if the new technique for the frontend development is also ok for you I would be happy to merge this PR :wink: :+1: 
Again many thanks for all those good ideas which you have implemented! It saves us some custom commits on top of our fork :+1:

2022-09-09 12:19 UTC, dmijatovic commented on nginx/nginx.conf
> +server {
@ruester Maybe this is not necessary? Next.js has proxy defined in next.config.js so it should proxy requests to http:localhost/image. Maybe enabling frontend-dev service on port 3000 and "re-defining" proxies is sufficient? I'll have look at this early next week. Important point is that this nginx.conf is used in the production image. If there is no other way than changing nginx.config we would need to have dev and prod nginx.conf files (and images).

2022-09-11 18:01 UTC, dmijatovic commented
@ruester I updated next config to properly proxy image, api and auth calls. I rebased to the latest main and needed to force push after that. This version should also work for you. Let me know if there are any other things we could improve.

We wait with merging of this PR until we have approval from @cmeessen, @ctwhome and @ewan-escience.

2022-09-12 07:10 UTC, ruester commented
> I updated next config to properly proxy image, api and auth calls.

Many thanks, it also works for our customization :+1:

2022-09-13 13:10 UTC, ruester approved these changes

2022-09-15 08:33 UTC, ewan-escience approved these changes
I tried it out without custom theme settings or volumes, and with the default theme everything still seems to work.

2022-09-15 10:41 UTC, ruester commented on Makefile
> +.PHONY: start install dev down dev-docs
is it good practice to list all targets here which are not a file to be generated, otherwise make checks the timestamp of a potential file (for example named "start") and will not execute those steps

> A phony target is one that is not really the name of a file; rather it is just a name for a recipe to be executed when you make an explicit request. There are two reasons to use a phony target: to avoid a conflict with a file of the same name, and to improve performance.

2022-09-15 10:43 UTC, ruester approved these changes

2022-09-15 10:43 UTC, ruester commented on Makefile
> +.PHONY: start install dev down dev-docs
```suggestion
.PHONY: start install frontend data dev down dev-docs
```

2022-09-15 10:46 UTC, ruester commented on frontend/package.json
>      "backend:dev": "docker-compose up --scale test=0"
does this really work, since there is no `docker-compose.yml` within the `frontend` directory? or is this left over from some previous developments?

2022-09-15 10:58 UTC, dmijatovic commented on frontend/package.json
>      "backend:dev": "docker-compose up --scale test=0"
Well spotted! I will remove it and implement your previous suggestion in a minute

2022-09-15 13:48 UTC, cmeessen approved these changes

2022-09-15 14:15 UTC, dmijatovic commented
@ctwhome and @jmaassen Can you have a look if the instructions in the README work on your machines and the text is clear?

2022-09-16 18:19 UTC, ctwhome commented on README.md
> +docker-compose up --scale frontend-dev=1 --scale scrapers=0 -d
❤️

2022-09-16 19:05 UTC, ctwhome requested changes
This is a very big PR and complex. The work put in here has been fantastic. I want to add a remark on how we could think of a way to isolate completely the variations for different organizations like Helmholtz in this case, but also be able to support other organizations as well in the future. 

There is a bit of confusion on how things are growing organically. The major drawfall I see is that different variations of the application coexist within the base code rather than outside the main application. This can be a problem in the future if other organizations want to create their own themes/variations. Some individual components have subfolders with the name of rsd or helmholtz  (/components/home/).

We need to give it the last push to try to isolate variations from the base code.

2022-09-16 19:24 UTC, ctwhome requested changes

2022-09-16 19:24 UTC, ctwhome commented on deployment/README.md
> +## Custom theme
this information should be in the documentation site

2022-09-21 08:55 UTC, jmaassen approved these changes
Go ahead and merge!

2022-09-21 08:56 UTC, merged