Feedback panel
research-software-directory/RSD-as-a-service pull request #571
Opened 2022-10-07 20:41 UTC by ctwhome

# Add a feedback panel at the app header

Fixes #557  and improves UX on dropdown menus at the app header
![image](https://user-images.githubusercontent.com/4195550/194648158-4d35d044-8920-48f6-82b4-947ad1db7d88.png)

Changes proposed in this pull request:

* Creation of quick access -always present - menu feedback. The user can write the message and an email will be generated with the **text** and the **URL location** when the feedback is written
* The text area is automatically selected after opening the feedback panel
* The message is saved in case the user clicks away from the form accidentally to avoid losing their message.
* It is possible to send an email or open the GitHub issues from the more information message

<img width="404" alt="image" src="https://user-images.githubusercontent.com/4195550/194648559-cc1ed712-ccc4-4c76-8702-8163a8666a85.png">

![image](https://user-images.githubusercontent.com/4195550/194649316-5e215c69-3fd9-457f-a913-82f2b39e3f10.png)

How to test:

* go to any page of the application and click on the menu feedback to open the form. Write a message and sen

PR Checklist:

*   [ ] Increase version numbers in `docker-compose.yml`
*   [*] Link to a GitHub issue
*   [ ] Update documentation
*   [ ] Tests

2022-10-07 20:43 UTC, ctwhome commented
the base URL is fixed to [https://github.com/research-software-directory/RSD-as-a-service/issues](https://github.com/research-software-directory/RSD-as-a-service/issues) @dmijatovic is there a way to get this from .env?

2022-10-10 07:40 UTC, cmeessen commented
That's a great idea to lower the barrier of sending feedback. I'd be happy if we could configure whether the feedback button should be shown at all, and which email address should be used.

Also, how about to directly store the feedback in the database? I can't really estimate how many problems we could get from bots or malicious attacks, but this would remove the barrier of having to send a mail. Some ideas to stop abuse of the function: minimum/max character count, limit amount of requests per minute for one user, limit total amount of requests per minute on server side. It would also come with some effort to make a frontend page for administrators to manage the reviews.

2022-10-10 11:52 UTC, ctwhome commented
thanks @cmeessen those are great suggestions. For now we will just go with the email but keeping in mind the admin panel for reviewing feedback, for example, and also adding a mail server to not have to open the users email to send the feedback. This should be only a remporal preliminary solution.

2022-10-11 14:02 UTC, ctwhome commented
@dmijatovic it seems to be like the env variable is not being catch up by the production version, on the dev (http://localhost:3000/) it works. I double check if the envs were exposed in the docker compose but I do'n tsee anything unusual. 
woudl you mind to double check it to see where could be the problem?

2022-10-20 13:46 UTC, dmijatovic commented on .env.example
> +NEXT_PUBLIC_FEEDBACK_URL=      # rsd@esciencecenter.nl
Please remove env variable. We use settings.json, property "feedback_url"

2022-10-20 13:47 UTC, dmijatovic commented on docker-compose.yml
> +      - NEXT_PUBLIC_FEEDBACK_URL
revemove "NEXT_PUBLIC_FEEDBACK_URL"

2022-10-20 14:06 UTC, ewan-escience requested changes
-  When commenting out `NEXT_PUBLIC_FEEDBACK_URL`, it still shows up. I heard this is not used anymore, because a build time variable from `frontend/config/defaultSettings.json` is used instead, so it can be removed from the `.env.example`.
- When sending the mail with Thunderbird, the message body is empty.
- The link to the GitHub issues doesn't seem to be configurable?

2022-10-21 11:03 UTC, dmijatovic approved these changes

2022-10-21 11:55 UTC, ewan-escience approved these changes
Thunderbird still doesn't work, but that seems to be unfixable.

2022-10-21 14:46 UTC, merged