63 on error no content message
research-software-directory/RSD-as-a-service pull request #64
Opened 2021-12-20 11:36 UTC by dmijatovic

# Pull request Title

Fixes #63 

How to test:

* start only frontend without backend and visit the software page. You should see the website and simple no content message in the middle of the page.

![image](https://user-images.githubusercontent.com/9204081/146761401-9b79b103-8f7a-49ad-8218-525617aabdfa.png)

2021-12-20 15:41 UTC, ewan-escience reviewed
It works as described. However, the "No content" on the software page looks different from the one at the project page. Not a deal breaker though, as we didn't have project content yet. But this must eventually be consistent. 

Also please try to put a newline at the end of each file.

2021-12-20 15:44 UTC, ctwhome commented
we need to lint-fix the code before committing. @dmijatovic  did you find the way to format the code with eslint (+ prettier) for next?

2021-12-20 15:49 UTC, ctwhome requested changes

2021-12-20 15:49 UTC, ctwhome commented on README.md
thanks for the docs

2021-12-20 15:49 UTC, ctwhome commented on frontend/utils/getSoftware.ts
>  }
I suggest to mode the external calls with fetching to a folder called API, utils can be confusing since is has a different meaning.

2021-12-20 15:51 UTC, ctwhome commented on frontend/utils/getSoftware.ts
>  }
Grid and cards are pure CSS components that we can make with tailwindcss, I would prefer that

2021-12-20 16:50 UTC, dmijatovic commented on frontend/utils/getSoftware.ts
>  }
> I suggest moving the external calls with fetching to a folder called 'api', utils can be confusing since is has a different meaning.

@ctwhome I think with Next calling the folder api might be confusing as it has api functionality. I would rather leave these function in utils, or maybe create folder data? Not sure.

2021-12-20 16:57 UTC, dmijatovic commented
> It works as described. However, the "No content" on the software page looks different from the one at the project page. Not a deal breaker though, as we didn't have project content yet. But this must eventually be consistent.
> 

Agree. The project "no-content" component will be the same as software "no-content" component.

> Also please try to put a newline at the end of each file.

Just runned default linter and it does not have rule for new line at the end of the file. I will look at the linter rules.

2021-12-20 18:51 UTC, ctwhome commented
We could make a nice illustration or similar, but for now it looks good to me, no errors!

2021-12-20 19:02 UTC, dmijatovic commented on frontend/utils/getSoftware.ts
>  }
> Grid and cards are pure CSS components that we can make with tailwindcss, I would prefer that

Is replaced with tailwind classes

2021-12-21 09:33 UTC, ewan-escience requested changes
See the comment

2021-12-21 09:33 UTC, ewan-escience commented on frontend/.eslintrc.json
>    }
Please add the rule `"indent": ["error", "tab"]`

2021-12-21 09:52 UTC, dmijatovic commented on frontend/.eslintrc.json
>    }
> Please add the rule `"indent": ["error", "tab"]`

Can we investigate this first and do it in separate PR? The default for frontend development is to use spaces. I have tried this couple of years ago and eventually reverted back to spaces because all defaults are set to spaces. In my experience it will require continuous linting and corrections.

2021-12-21 10:33 UTC, ctwhome approved these changes

2021-12-21 11:40 UTC, ewan-escience approved these changes

2021-12-21 11:44 UTC, merged