Allow user to delete account from RSD
research-software-directory/RSD-as-a-service pull request #752
Opened 2023-02-27 17:42 UTC by dmijatovic

# Admin section and allow user to remove account

Closes #740 

Changes proposed in this pull request:
* Added remove account button at the user profile page
* Created rsd admin section with the menu options on the left side
* Added rsd accounts section where rsd_admin can remove account

How to test:
* `make start`: to rebuild app
* login as user, navigate to your settings (from user menu). User remove account button. Your account will removed and you will be logged out. Note! The when user logs in next time the account will be recreated. 
* login as rsd_admin. Navigate to administration, rsd users section. You will see the list of RSD accounts. You can search by user name, email or organisation. You can remove any account as rsd_admin. NOTE! This will not prevent user from being able to login, however all maintainer permissions for this account will be removed as well as all maintainer invites this user has created or claimed.

## Remove account

![image](https://user-images.githubusercontent.com/9204081/221640170-682a5b76-1563-40c4-b464-df614c01fc7f.png)

## RSD admin section

![image](https://user-images.githubusercontent.com/9204081/221641509-8f3dce15-e8b3-4010-8cfb-2491d57e5d2e.png)

PR Checklist:

*   [ ] Increase version numbers in `docker-compose.yml`
*   [ ] Link to a GitHub issue
*   [ ] Update documentation
*   [ ] Tests

2023-02-28 09:30 UTC, cmeessen requested changes
This is great work, thank you for implementing the account removal so quickly :+1:

2023-02-28 09:30 UTC, cmeessen commented on frontend/config/userMenuItems.tsx
>        icon: <PlaylistAddCheckIcon />
I think this can be removed because it is now included in the "Administration" link above?

2023-02-28 09:30 UTC, cmeessen commented on frontend/components/admin/rsd-users/RsdLoginList.tsx
> +            {name}{email ? `, ${email}`:''}{home_organisation ? `, ${home_organisation}`:''} {provider ? `, ${provider}`:''}
```suggestion
            {name}{email ? `, ${email}`:''}{home_organisation ? `, ${home_organisation}`:'NULL'} {provider ? `, ${provider}`:''}
```

This would help us to better identify people that login via social IDPs integrated in the AAI.

2023-02-28 09:30 UTC, cmeessen submitted a review, later dismissed
This is great work, thank you for implementing the account removal so quickly :+1:

2023-02-28 09:52 UTC, dmijatovic commented on frontend/config/userMenuItems.tsx
>        icon: <PlaylistAddCheckIcon />
Maybe we can leave it as quick access link? Let's see what others think about removing it

2023-02-28 09:56 UTC, dmijatovic commented on frontend/components/admin/rsd-users/RsdLoginList.tsx
> +            {name}{email ? `, ${email}`:''}{home_organisation ? `, ${home_organisation}`:''} {provider ? `, ${provider}`:''}
Currently I just show values if these are present without any labels (eg. email, organisation). I not sure that NULL would would have proper meaning without a clear label. Maybe use some other value to clearly indicate that?

2023-02-28 14:56 UTC, ewan-escience requested changes
It is a bit weird that as an admin, you can delete your own account from the list.

2023-02-28 14:56 UTC, ewan-escience commented on frontend/components/admin/rsd-users/RemoveAccountMessage.tsx
> +export const whatWillBeRemoved = `
I would change this to have a different message for deleting your own account and deleting an account as an admin. For your own: 

`Are you sure you want to completely remove your account? All data related to your account will be deleted: you won't be able to access software, projects and organisations that you were a maintainer of, and unused maintainer invitations will be deleted. The software, project and organisation pages will not be removed from the RSD.`

And as an admin: 
`Are you sure you want to delete the account ${uuid}? The owner will lose access to all pages they maintained and all unused maintainer invites they created will be deleted.`

If other people have better suggestions, I'd like to hear those too.

2023-02-28 15:42 UTC, dmijatovic commented on frontend/components/admin/rsd-users/RemoveAccountMessage.tsx
> +export const whatWillBeRemoved = `
Nice suggestion! 
I assume these are text to use in the confirmation modal.
Maybe use "...to edit software..." instead of "...to access software...".
Maybe add "you created" to "...unused maintainer invitations, **you created**, will be deleted..."

What about notification text on the user settings page? Maybe we can use same text without first sentence/question?

"All data related to your account will be deleted: you won't be able to access software, projects and organisations that you were a maintainer of, and unused maintainer invitations you created will be deleted. The software, project and organisation pages will not be removed from the RSD."

2023-03-03 10:40 UTC, jmaassen commented
Some text improvements: 

The orange warning block for a user now says: 

**Remove account**

<!> Removing your RSD account

All data related to your account will be deleted: you won't be able to edit software, projects and organisations that you were a maintainer of. All unused maintainer invitations created by you will be deleted. The software, project and organisation pages will not be removed from the RSD.

A better text may be: 

**Remove account**

<!> This will remove your RSD account

Your account will be deleted. You will no longer be able to edit software, projects and organisations that you are a maintainer of. All unused maintainer invitations created by you will be deleted. The software, project and organisation pages you currently maintain will **not** be removed from the RSD.

2023-03-03 10:45 UTC, jmaassen commented
For the administrator popup it now says: 

The owner will lose access to all pages they maintained and all unused maintainer invites they created will be deleted.

Better text may be: 

The owner will lose access to all pages they maintain and all unused maintainer invites they have created will be deleted.

2023-03-03 10:48 UTC, jmaassen commented
Unrelated thing I noticed: 

When I log in as a new user, I do not get the TOS popup until I try to add something to the RSD. This is a bit weird, as you would expect this popup to appear upon the first login, not the first action?

2023-03-03 11:41 UTC, jmaassen approved these changes

2023-03-03 11:47 UTC, ewan-escience approved these changes

2023-03-03 12:23 UTC, merged