555 package managers
research-software-directory/RSD-as-a-service pull request #791
Opened 2023-03-22 20:06 UTC by dmijatovic

# Software maintainers can add software downloading/installation locations

Closes #555

Changes proposed in this pull request:
* Software maintainer can define "Package managers" to point to locations from where software can be installed.
* RSD will try to extract package manager "type" based on url provided and store it.
* RSD scrapers will try to extract additional stats (downloads and dependencies) from package manager api's when possible. Supported package managers are: anaconda, cran, dockerhub, github, maven, npm, pypi and other (not supported).
* Deep linking to software edit pages are implemented. The user can link to edit/contributors, edit organisations page etc,
* Drag and drop item resizing (scewness) is fixed and the ui responsiveness on position change is improved

How to test:
* `make start` to rebuild app and create test data
* login as rsd_admin to be able to change existing test data
* navigate to edit software,
* confirm that position change of contributor item is working properly. Change order and view page
* confirm deep linking is working by using back button from the software which should take you back to edit contributors page
* navigate to edit software, package managers page. Add number of locations: 
   * anaconda location: https://anaconda.org/anaconda/spyder
   * CRAN: https://cran.r-project.org/web/packages/abglasso/index.html
   * dockerhub: https://hub.docker.com/r/swaggerapi/swagger-ui
   * github: https://github.com/research-software-directory/RSD-as-a-service/pkgs/container/rsd-saas%2Fdatabase
   * maven: https://repo.maven.apache.org/maven2/asm/
   * npm: https://www.npmjs.com/package/npm
   * pypi: https://pypi.org/project/panda-model/
   * any other url will be defined as "other"

PR Checklist:

*   [ ] Increase version numbers in `docker-compose.yml`
*   [ ] Link to a GitHub issue
*   [ ] Update documentation
*   [ ] Tests

2023-03-24 10:31 UTC, jmaassen requested changes
It seems that the wrong maven URL is being used? One that points to an apache repo?

This is a maven central repo:

https://mvnrepository.com/artifact/junit/junit

2023-03-24 11:09 UTC, dmijatovic commented
> It seems that the wrong maven URL is being used? One that points to an apache repo?
> 
> This is a maven central repo example:
> 
> https://mvnrepository.com/artifact/junit/junit

Good point! 

Can we validate that all hostnames/domains of package manager used for detection are correct? 
I added the list am using now to PR description

2023-03-24 11:24 UTC, ewan-escience commented
The rest of the list in the PR is correct.

2023-03-27 09:39 UTC, ewan-escience approved these changes

2023-03-27 10:23 UTC, merged