fix: Helmholtz AAI handling if only one eduperson_entitlement is returned
research-software-directory/RSD-as-a-service pull request #858
Opened 2023-04-27 13:24 UTC by cmeessen

# Fix issue in Helmholtz AAI login

Fixes #857 

Changes proposed in this pull request:

* append to JSONArray in case of `ClassCastException`

How to test:

* enable Helmholtz AAI login provider and in `.env` set `HELMHOLTZAAI_ALLOW_EXTERNAL_USERS=false`
* `docker compose build --parallel && docker compose up --scale scrapers=0`
* login via Helmholtz AAI using a social IdP (Google, ORCID or GitHub)
* check that auth does not log any errors
* the user will be presented the correct error message: "You are not allowed to login."

PR Checklist:

*   [ ] Increase version numbers in `docker-compose.yml`
*   [x] Link to a GitHub issue
*   [ ] Update documentation
*   [ ] Tests

2023-04-28 08:56 UTC, dmijatovic approved these changes
It works as described.

2023-05-01 08:07 UTC, ewan-escience requested changes
A small code practice request.

2023-05-01 08:07 UTC, ewan-escience commented on authentication/src/main/java/nl/esciencecenter/rsd/authentication/HelmholtzAaiLogin.java
> +		try {
It would be better to test if it is a `JSONArray` with `instanceof`, e.g.
```java
Object edupersonClaim = userInfo.getClaim("eduperson_entitlement");
if (edupersonClaim instanceof JSONArray) {
// do something
}
```

2023-05-02 11:48 UTC, cmeessen commented on authentication/src/main/java/nl/esciencecenter/rsd/authentication/HelmholtzAaiLogin.java
> +		try {
Done

2023-05-03 11:10 UTC, ewan-escience approved these changes

2023-05-03 11:29 UTC, merged