Imperial auth
research-software-directory/RSD-as-a-service pull request #944
Opened 2023-07-19 19:05 UTC by cc-a

This PR implements an authentication option for Imperial College London with Azure Active Directory.

*  

How to test:

* In principle could be tested against any Azure AD tenant using details of a registered application.

PR Checklist:

*   [ ] Increase version numbers in `docker-compose.yml`
*   [ ] Link to a GitHub issue
*   [ ] Update documentation
*   [ ] Tests

2023-07-25 16:37 UTC, cc-a commented
I'd like to run this against the CI before writing up as a full pull request. @jmaassen could you please grant the necessary approval for the CI runs?

2023-08-07 08:09 UTC, dmijatovic commented
@cc-a All checks are passing. Can we review this PR?

2023-08-07 08:21 UTC, cc-a commented
Yes please @dmijatovic

2023-08-08 08:31 UTC, ewan-escience commented
The env variable `IMPERIAL_LOGIN_PROMPT` is not yet in the (frontend part of) `docker-compose.yml`, which makes it use the unsupported value `login+consent`.

Furthermore, can you add all the env variables to `deployment/docker-compose.yml` as well?

Is it correct that this implementation can be used as a general Azure AAD implementation? If so, we should rename it as such.

I'm trying to test it out with personally registered app credentials, but Microsoft [changed their policy](https://learn.microsoft.com/en-gb/azure/active-directory/develop/publisher-verification-overview#requirements) and I cannot login yet. I'll see if I can work around it somehow.

2023-08-08 13:13 UTC, dmijatovic commented
@cc-a Maybe is useful to join one of our daily stand-ups (at 10 am CET) to discuss our remarks and next steps? 
We can send you invite to our teams session.

2023-08-08 13:44 UTC, cc-a commented
Thanks for the feedback @ewan-escience and @dmijatovic. I'll drop by the standup tomorrow morning to discuss.

2023-08-09 11:37 UTC, cc-a commented
I've pushed the updates we discussed @dmijatovic @ewan-escience. Seems to be waiting for approval to run the workflows again :thinking:

2023-08-09 12:39 UTC, ewan-escience commented
Looks mostly good, just a few small things.

- Can you fill in the value `http://localhost/auth/login/azure` for `AZURE_REDIRECT` in `.env.example`?
- Can you `AZURE` to the allowed values of line 61 of `.env.example`?
- Can you copy the new env variables from `docker-compose.yml` to `deployment/docker-compose.yml`?

Hopefully @dmijatovic can look at the frontent code tomorrow and add the new redirect link to his testing Azure application.

2023-08-10 07:57 UTC, dmijatovic commented on .env.example
Please add AZURE to the list of providers, something like this
```
RSD_AUTH_PROVIDERS=SURFCONEXT;ORCID;AZURE;LOCAL
```

2023-08-10 08:43 UTC, dmijatovic commented on frontend/pages/api/fe/auth/azure.ts
> +      html: process.env.AZURE_DESCRIPTION_HTML || "Login with your institutional credentials."
Please use single quotes (') for strings. You can run eslint linter checks locally and fix these automatically :-).

```bash
# run linter locally to check for warnings and errors
yarn lint
# fix automatically warnings
yarn lint --fix
```

2023-08-10 08:51 UTC, dmijatovic requested changes
**Excellent work!** I tested with my Azure account and the implementation works properly in my case too. It seems to me generic enough to be used with any Azure AD tenant+app.

There are few cosmetic improvements. I commented on improvement suggestions in the code directly (see my comments). 

I usually run linter and tests locally before I create PR. You can run following commands from then `frontent` folder.

```bash
# run unit tests locally (check if some test are broken by last changes)
yarn test
# run linter locally (check for warnings and errors -> errors are fatal and building of frontend will fail)
yarn lint
```

2023-08-10 10:25 UTC, cc-a commented
Awesome. Thanks both. I've made (hopefully) the final tweaks.

2023-08-10 10:43 UTC, ewan-escience approved these changes
Nice work! In principle, it works for me.

When inspecting the database though, I noticed that `home_organisation` was `null`. You try to get the home organisation from `Config.azureOrganisation()`, whish uses the env variable `AZURE_ORGANISATION`, which is neither in the `.env.example` or in the two `docker-compose.yml` files.

I'm approving this PR in case you want to keep it this way for now and fix it later, but also feel free to fix it now. Please let us know what you want to do, so we know when to merge this PR.

2023-08-10 11:20 UTC, dmijatovic approved these changes
Again, excellent work. Thank you for your contribution :+1: 
As Ewan mentioned let us know when this PR can be merged.

2023-08-10 13:47 UTC, cc-a commented
Cool. I've added the missing entries for AZURE_ORGANISATION to `.env.example` and the docker compose files and tested. I think this now be ready to merg.

2023-08-11 08:03 UTC, merged